// Claves IATA para los aeropuertos de México

// Se modificó la primera base de datos para generalizar el estado de México y conseguir una respuesta de una API
const clavesIATAmex = {
  AGU: "Aguascalientes",
  CDI: "Baja California",
  ESE: "Baja Californiaa",
  MXL: "Baja California",
  SFH: "Baja California",
  TIJ: "Tijuana",
  CSL: "Baja California Sur",
  CUA: "Baja California",
  GUB: "Baja California",
  LAP: "Baja California",
  LTO: "Baja California",
  MUG: "Baja California",
  PVP: "Baja California",
  SJD: "Baja California",
  CME: "Campeche",
  CPE: "Campeche",
  CJT: "Chiapas",
  PJP: "Chiapas",
  PQM: "Chiapas",
  SZT: "Chiapas",
  TAP: "Chiapas",
  TMG: "Chiapas",
  TGZ: "Chiapas",
  CJS: "Chihuahua",
  CUU: "Chihuahua",
  NCG: "Chihuahua",
  ACN: "Coahuila"	,
  LOV: "Coahuila",
  PDS: "Coahuila",
  SLW: "Coahuila"	,
  TRC: "Coahuila",
  CLQ: "Colima",
  ZLO: "Colima",
  MEX: "Mexico",
  DGO: "Durango",
  TLC: "Toluca",
  GUA: "Guanajuato",
  CYW: "Guanajuato",
  ACA: "Guerrero",
  PIE: "Guerrero",
  ZIH: "Guerrero",
  PCA: "Hidalgo",
  GDL: "Jalisco",
  LOM: "Jalisco",
  PVR: "Jalisco",
  TUX: "Jalisco",
  ZAP: "Jalisco",
  JJC: "Mexico",
  SLM: "Mexico",
  AZG: "Michoacan",
  LZC: "Michoacan",
  MLM: "Michoacan",
  UPN: "Michoacan",
  ZMM: "Michoacan",
  CVJ: "Morelos",
  TNY: "Nayarit",
  TPQ: "Nayarit",
  MTY: "Monterrey",
  NTR: "Monterrey",
  HUX: "Oaxaca",
  IZT: "Oaxaca",
  OAX: "Oaxaca",
  PXM: "Oaxaca",
  SCX: "Oaxaca",
  TNC: "Puebla",
  QRO: "Queretaro",
  CTM: "Quintana Roo",
  CUN: "Cancun",
  CZM: "Quintana Roo",
  ISJ: "Quintana Roo",
  TUY: "Quintana Roo",
  SLP: "San Luis Potosi",
  TCN: "San Luis Potosi",
  CNA: "Sonora",
  CUL: "Sinaloa",
  LMM: "Sinaloa",
  MZT: "Sinaloa",
  NAV: "Sonora",
  PPE: "Sonora",
  TCP: "Sinaloa",
  UAC: "Sonora",
  XAL: "Sonora",
  CEN: "Sonora",
  GYM: "Sonora",
  HMO: "Sonora",
  NOG: "Sonora",
  CPX: "Tabasco",
  VSA: "Tabasco",
  CVM: "Tamaulipas",
  MMC: "Tamaulipas",
  MAM: "Tamaulipas",
  NLD: "Tamaulipas",
  REX: "Tamaulipas",
  TAM: "Tamaulipas",
  JAL: "Veracruz",
  MTT: "Veracruz",
  PAZ: "Veracruz",
  VER: "Veracruz",
  CZA: "Yucatan	",
  MID: "Merida",
  TZM: "Yucatán",
  ZCL: "Zacatecas",
}

module.exports.clavesIATAmex = clavesIATAmex;
