// Claves IATA para los aeropuertos de México

const clavesIATAmex = {
  AGU: "Aguascalientes",
  CDI: "Baja California",
  ESE: "Baja California	Ensenada",
  MXL: "Baja California	Mexicali",
  SFH: "Baja California	San Felipe",
  TIJ: "Tijuana",
  CSL: "Cabo San Lucas",
  CUA: "Baja California Sur	Ciudad Constitución",
  GUB: "Baja California Sur	Guerrero Negro",
  LAP: "Baja California Sur	La Paz",
  LTO: "Baja California Sur	Loreto",
  MUG: "Baja California Sur	Mulegé",
  PVP: "Baja California Sur	Santa Rosalía",
  SJD: "Baja California Sur	Los Cabos",
  CME: "Campeche	Cd. Del Carmen",
  CPE: "Campeche	Campeche",
  CJT: "Chiapas	Comitán",
  PJP: "Chiapas	Pijijiapan",
  PQM: "Chiapas	Palenque",
  SZT: "Chiapas	San Cristobal de las Casas",
  TAP: "Chiapas	Tapachula",
  TMG: "Chiapas	Tuxtla Gutiérrez",
  TGZ: "Chiapas	Tuxtla Gutiérrez",
  CJS: "Chihuahua	Cd. Juárez",
  CUU: "Chihuahua	Chihuahua",
  NCG: "Chihuahua	Nuevo Casas",
  ACN: "Coahuila	Ciudad Acuña"	,
  LOV: "Coahuila	Frontera",
  PDS: "Coahuila	Piedras Negras",
  SLW: "Coahuila	Saltillo"	,
  TRC: "Coahuila	Torreón",
  CLQ: "Colima	Colima",
  ZLO: "Colima	Manzanillo",
  MEX: "Cd. de México",
  DGO: "Durango	Durango",
  TLC: "Toluca",
  GUA: "Guanajuato",
  CYW: "Guanajuato	Celaya",
  ACA: "Guerrero	Acapulco",
  PIE: "Guerrero	Acapulco",
  ZIH: "Guerrero	Ixtapa/Zihuatanejo",
  PCA: "Hidalgo	Pachuca",
  GDL: "Jalisco	Guadalajara",
  LOM: "Jalisco	Lagos de Moreno",
  PVR: "Jalisco	Puerto Vallarta",
  TUX: "Jalisco	Tuxpan",
  ZAP: "Jalisco	Zapopan",
  JJC: "México	Atizapán",
  SLM: "México	Zumpango",
  AZG: "Michoacán	Apatzingán",
  LZC: "Michoacán	Lázaro Cárdenas",
  MLM: "Michoacán	Morelia",
  UPN: "Michoacán	Uruapan",
  ZMM: "Michoacán	Zamora",
  CVJ: "Morelos	Cuernavaca",
  TNY: "Nayarit	Tepic",
  TPQ: "Nayarit	Tepic",
  MTY: "Nuevo León	Monterrey",
  NTR: "Nuevo León	Monterrey",
  HUX: "Oaxaca	Huatulco",
  IZT: "Oaxaca	Ixtepec",
  OAX: "Oaxaca",
  PXM: "Oaxaca	Puerto Escondido",
  SCX: "Oaxaca	Salina Cruz",
  TNC: "Puebla	Tehuacán",
  QRO: "Querétaro	Querétaro",
  CTM: "Quintana Roo	Chetumal",
  CUN: "Quintana Roo	Cancún",
  CZM: "Quintana Roo	Cozumel",
  ISJ: "Quintana Roo	Isla Mujeres",
  TUY: "Quintana Roo	Tulum",
  SLP: "San Luis Potosí	San Luis Potosí",
  TCN: "San Luis Potosí	Tamuín",
  CNA: "Sonora	Cananea",
  CUL: "Sinaloa	Culiacán",
  LMM: "Sinaloa	Los Mochis",
  MZT: "Sinaloa	Mazatlán",
  NAV: "Sonora	Navojoa",
  PPE: "Sonora	Puerto Peñasco",
  TCP: "Sinaloa	Teacapán",
  UAC: "Sonora	San Luis Río Colorado",
  XAL: "Sonora	Álamos",
  CEN: "Sonora	Cd. Obregón",
  GYM: "Sonora	Guaymas",
  HMO: "Sonora	Hermosillo",
  NOG: "Sonora	Nogales",
  CPX: "Tabasco	Ciudad Pemex",
  VSA: "Tabasco	Villahermosa",
  CVM: "Tamaulipas	Cd. Victoria",
  MMC: "Tamaulipas	Ciudad Mante",
  MAM: "Tamaulipas	Matamoros",
  NLD: "Tamaulipas	Nuevo Laredo",
  REX: "Tamaulipas	Reynosa",
  TAM: "Tamaulipas	Tampico",
  JAL: "Veracruz	Xalapa",
  MTT: "Veracruz	Minatitlán",
  PAZ: "Veracruz	Poza Rica",
  VER: "Veracruz",
  CZA: "Yucatán	Chichén Itzá",
  MID: "Yucatán	Mérida",
  TZM: "Yucatán	Tizimín",
  ZCL: "Zacatecas	Zacatecas",
}

module.exports.clavesIATAmex = clavesIATAmex;
